/**
 * OpporHub AI Career Operating System — AI Gateway Service
 * Provides a simplified complete() and stream() API backed by the unified AIRouter.
 * Provider: OpenAI gpt-4o-mini (client-mandated).
 */

import { aiRouter, AITask } from './aiRouter.service';
import { logger } from '../core/telemetry/logger.service';

export interface AIOptions {
  task?: AITask;
  temperature?: number;
  maxTokens?: number;
}

export class AIGatewayService {
  /**
   * Completes a prompt using the AI Router (gpt-4o-mini).
   * Accepts a structured system + user prompt pair for best results.
   */
  public async complete(
    systemPrompt: string,
    userPrompt: string,
    options?: AIOptions
  ): Promise<string> {
    const task: AITask = options?.task || 'GENERIC_COMPLETION';
    logger.info({ task, service: 'AIGatewayService' }, 'Executing AI Gateway completion');

    const result = await aiRouter.complete({
      task,
      systemPrompt,
      userPrompt,
      temperature: options?.temperature,
      maxTokens: options?.maxTokens,
      jsonMode: false,
    });

    return result.text;
  }

  /**
   * Real SSE streaming — yields text chunks as generated by the model.
   * Accepts a structured system + user prompt pair.
   */
  public async stream(
    systemPrompt: string,
    userPrompt: string,
    onChunk: (text: string) => void,
    options?: AIOptions
  ): Promise<void> {
    const task: AITask = options?.task || 'GENERIC_COMPLETION';
    logger.info({ task, service: 'AIGatewayService' }, 'Starting AI Gateway stream');

    for await (const chunk of aiRouter.stream({
      task,
      systemPrompt,
      userPrompt,
      temperature: options?.temperature,
      maxTokens: options?.maxTokens,
    })) {
      onChunk(chunk);
    }
  }
}

export const aiGatewayService = new AIGatewayService();
